// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP7A8w2-M16fWoKUm6VmMfHIiO6BlGxLk',
    appId: '1:344276650107:web:5b0a1c8b03871876c8bade',
    messagingSenderId: '344276650107',
    projectId: 'quiz-31a1c',
    authDomain: 'quiz-31a1c.firebaseapp.com',
    storageBucket: 'quiz-31a1c.firebasestorage.app',
    measurementId: 'G-ZK1F7QY920',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy9XRoA9bUw1UIlKO8oStZrkRsggT205E',
    appId: '1:344276650107:android:e83b21fd0f0097e8c8bade',
    messagingSenderId: '344276650107',
    projectId: 'quiz-31a1c',
    storageBucket: 'quiz-31a1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgwOM0O7SnesR8ysI1dQLllQArYJnsV7c',
    appId: '1:344276650107:ios:e1973350e9893f1bc8bade',
    messagingSenderId: '344276650107',
    projectId: 'quiz-31a1c',
    storageBucket: 'quiz-31a1c.firebasestorage.app',
    iosBundleId: 'com.example.quiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgwOM0O7SnesR8ysI1dQLllQArYJnsV7c',
    appId: '1:344276650107:ios:e1973350e9893f1bc8bade',
    messagingSenderId: '344276650107',
    projectId: 'quiz-31a1c',
    storageBucket: 'quiz-31a1c.firebasestorage.app',
    iosBundleId: 'com.example.quiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCP7A8w2-M16fWoKUm6VmMfHIiO6BlGxLk',
    appId: '1:344276650107:web:27d658793b2746b0c8bade',
    messagingSenderId: '344276650107',
    projectId: 'quiz-31a1c',
    authDomain: 'quiz-31a1c.firebaseapp.com',
    storageBucket: 'quiz-31a1c.firebasestorage.app',
    measurementId: 'G-Z5MR8FBMEP',
  );
}
